/**
 * GitHub API integration for creating Pull Requests
 */

const GITHUB_TOKEN = process.env.GITHUB_TOKEN || '';

export interface PullRequestResult {
  url: string;
  number: number;
  title: string;
}

/**
 * Create a Pull Request on GitHub.
 */
export async function createPullRequest(opts: {
  cloneUrl: string;  // e.g., https://github.com/user/repo.git
  headBranch: string;
  baseBranch: string;
  title: string;
  body: string;
  accessToken?: string;
}): Promise<PullRequestResult> {
  const token = opts.accessToken || GITHUB_TOKEN;
  if (!token) {
    throw new Error('GitHub token required to create PR');
  }

  // Extract owner/repo from clone URL
  const match = opts.cloneUrl.match(/github\.com[/:]([\w.-]+)\/([\w.-]+?)(?:\.git)?$/);
  if (!match) {
    throw new Error(`Cannot parse GitHub owner/repo from: ${opts.cloneUrl}`);
  }

  const [, owner, repo] = match;

  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
    method: 'POST',
    headers: {
      'Authorization': `token ${token}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      title: opts.title,
      body: opts.body,
      head: opts.headBranch,
      base: opts.baseBranch,
    }),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(`GitHub API error ${response.status}: ${errorBody}`);
  }

  const pr = await response.json() as any;

  return {
    url: pr.html_url,
    number: pr.number,
    title: pr.title,
  };
}

/**
 * Format a PR body with job details, safety score, and summary.
 */
export function formatPRBody(opts: {
  taskTitle: string;
  taskDescription: string;
  planSummary: string;
  diffSummary: string;
  safetyScore: number;
  concerns: string[];
  testResults?: string;
}): string {
  const safetyEmoji = opts.safetyScore >= 0.8 ? '🟢'
    : opts.safetyScore >= 0.5 ? '🟡'
    : '🔴';

  let body = `## 🤖 AutoCode Agent PR

### Task
**${opts.taskTitle}**
${opts.taskDescription}

### Plan
${opts.planSummary}

### Changes Summary
${opts.diffSummary}

### Safety Assessment
${safetyEmoji} **Score: ${(opts.safetyScore * 100).toFixed(0)}%**
`;

  if (opts.concerns.length > 0) {
    body += `\n#### ⚠️ Concerns\n${opts.concerns.map(c => `- ${c}`).join('\n')}\n`;
  }

  if (opts.testResults) {
    body += `\n### Test Results\n\`\`\`\n${opts.testResults.slice(0, 2000)}\n\`\`\`\n`;
  }

  body += `\n---\n*Generated by [AutoCode](https://autocode.dev) — Autonomous Coding Infrastructure*`;

  return body;
}
